repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # Use latest stable
    hooks:
      - id: end-of-file-fixer
        files: \.(scala|xml|js|css)$

  - repo: local
    hooks:
      - id: scalafmtAll
        name: "Run Scala and XML Formatters"
        entry: make format
        language: system
        pass_filenames: false

      - id: scalatests
        name: "Run Scala Tests"
        entry: make test
        language: system
        pass_filenames: false
